CREATE TABLE IF NOT EXISTS intelligence_evidence (
  id text PRIMARY KEY,
  owner_user_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  job_id text NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  task_id text NOT NULL REFERENCES intelligence_task(id) ON DELETE CASCADE,
  capability_id text NOT NULL REFERENCES canonical_capability(id) ON DELETE RESTRICT,
  implementation_id text NOT NULL,
  provider text NOT NULL,
  subject_kind text NOT NULL CHECK (subject_kind IN ('token','wallet','protocol','stablecoin')),
  subject_query text NOT NULL,
  network text,
  address text,
  status text NOT NULL CHECK (status IN ('verified','partial','unavailable','error')),
  summary text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_url text,
  observed_at timestamptz NOT NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  freshness_seconds integer,
  provider_confidence numeric,
  derivation_version text,
  limitations jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS intelligence_evidence_owner_job_idx ON intelligence_evidence(owner_user_id,job_id,fetched_at DESC);
CREATE INDEX IF NOT EXISTS intelligence_evidence_capability_idx ON intelligence_evidence(capability_id,provider,fetched_at DESC);
CREATE INDEX IF NOT EXISTS intelligence_evidence_subject_idx ON intelligence_evidence(subject_kind,network,address,fetched_at DESC);

INSERT INTO canonical_capability (id,name,purpose,effect,authority_requirement,value_at_risk_class,input_schema,output_schema,lifecycle_status) VALUES
('token.market.read','Token market read','Read current token price, market capitalization, volume and related market context from approved providers.','read','none','none','{"type":"object","properties":{"asset":{"type":"string"},"network":{"type":"string"},"address":{"type":"string"}}}','{"type":"object"}','limited-production'),
('token.liquidity.analyze','Token liquidity analysis','Analyze token DEX liquidity, pools, venue distribution and trading activity from approved providers.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('token.holders.analyze','Token holder analysis','Analyze holder concentration and distribution using approved onchain intelligence providers.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('token.deployer.analyze','Token deployer analysis','Resolve token creator/deployer evidence and inspect associated public onchain context without asserting identity beyond evidence.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('token.security.assess','Token security assessment','Collect provider-attributed token contract/security signals and explain their implications without declaring a token safe.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('wallet.profile','Wallet profile','Read a wallet profile and current public onchain state from approved providers.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('wallet.performance.analyze','Wallet performance analysis','Analyze historical wallet trading performance from approved providers.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('wallet.activity.analyze','Wallet activity analysis','Analyze wallet transactions, flows and public activity from approved providers.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('smartmoney.flow.read','Smart-money flow read','Read provider-defined smart-money capital flows while preserving provider attribution and cohort definitions.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('smartmoney.accumulation.detect','Smart-money accumulation detection','Derive bounded accumulation/distribution signals from preserved smart-money flow evidence.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('wallet.cluster.analyze','Wallet relationship analysis','Analyze first-degree wallet relationships and holder clusters without asserting common ownership.','read','none','none','{"type":"object"}','{"type":"object"}','tested'),
('token.smartmoney.read','Token smart-money read','Read provider-defined smart-money holdings and activity for a specific token.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('protocol.tvl.read','Protocol TVL read','Read provider-normalized protocol TVL and chain/category distribution.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('protocol.yield.read','Protocol yield read','Read current public DeFi yield-pool observations with protocol, chain, asset and TVL context.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('protocol.metrics.read','Protocol metrics read','Read normalized protocol metadata and public operating metrics from approved providers.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('stablecoin.supply.read','Stablecoin supply read','Read stablecoin supply and chain distribution observations.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production'),
('stablecoin.market.read','Stablecoin market read','Read stablecoin market and peg context from approved providers.','read','none','none','{"type":"object"}','{"type":"object"}','limited-production')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,purpose=EXCLUDED.purpose,effect=EXCLUDED.effect,authority_requirement=EXCLUDED.authority_requirement,value_at_risk_class=EXCLUDED.value_at_risk_class,input_schema=EXCLUDED.input_schema,output_schema=EXCLUDED.output_schema,lifecycle_status=EXCLUDED.lifecycle_status,updated_at=now();

INSERT INTO capability_implementation (id,canonical_capability_id,provider,name,version,supported_networks,pricing,trust_status,health_status,invocation_kind,known_failure_states,priority,enabled,environment_eligibility) VALUES
('coingecko-token-market-v1','token.market.read','coingecko','CoinGecko token market data','v3','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"keyRequired":true}','provider-verified','unknown','direct-http-json','["rate-limited","asset-resolution-failed","provider-unavailable"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('dexscreener-token-market-v1','token.market.read','dexscreener','DEX Screener token market data','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":false,"keyRequired":false}','provider-verified','healthy','direct-http-json','["rate-limited","asset-resolution-failed"]',20,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('dexscreener-liquidity-v1','token.liquidity.analyze','dexscreener','DEX Screener liquidity analysis','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":false,"keyRequired":false}','provider-verified','healthy','direct-http-json','["rate-limited","asset-resolution-failed"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('birdeye-market-solana-v1','token.market.read','birdeye','Birdeye Solana token overview','v1','["solana"]','{"metered":true,"keyRequired":true}','provider-verified','unknown','direct-http-json','["rate-limited","provider-unavailable"]',15,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('birdeye-liquidity-solana-v1','token.liquidity.analyze','birdeye','Birdeye Solana liquidity overview','v1','["solana"]','{"metered":true,"keyRequired":true}','provider-verified','unknown','direct-http-json','["rate-limited","provider-unavailable"]',15,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('nansen-token-holders-v1','token.holders.analyze','nansen','Nansen Token God Mode holders','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"creditClass":5,"keyRequired":true}','provider-verified','unknown','direct-http-json','["payment-required","rate-limited","provider-unavailable"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('bubblemaps-token-holders-v1','token.holders.analyze','bubblemaps','Bubblemaps token holders','v0','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"keyRequired":true}','provider-verified','unknown','direct-http-json','["rate-limited","provider-unavailable"]',20,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('birdeye-token-holders-solana-v1','token.holders.analyze','birdeye','Birdeye Solana token holders','v3','["solana"]','{"metered":true,"keyRequired":true}','provider-verified','unknown','direct-http-json','["rate-limited","provider-unavailable"]',30,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('blockscout-token-holders-v1','token.holders.analyze','blockscout','Blockscout token holder verification','v2','["ethereum","base","arbitrum"]','{"metered":false,"keyRequired":false}','provider-verified','healthy','direct-http-json','["network-unsupported","rate-limited"]',40,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('goplus-token-deployer-v1','token.deployer.analyze','goplus','GoPlus creator/owner intelligence','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"keyRequired":true}','provider-verified','unknown','direct-http-json','["rate-limited","provider-unavailable"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('goplus-token-security-v1','token.security.assess','goplus','GoPlus token security signals','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"keyRequired":true}','provider-verified','unknown','direct-http-json','["rate-limited","provider-unavailable"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('nansen-wallet-profile-v1','wallet.profile','nansen','Nansen wallet current-balance profile','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"creditClass":1,"keyRequired":true}','provider-verified','unknown','direct-http-json','["payment-required","rate-limited"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('nansen-wallet-performance-v1','wallet.performance.analyze','nansen','Nansen wallet PnL summary','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"creditClass":1,"keyRequired":true}','provider-verified','unknown','direct-http-json','["payment-required","rate-limited"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('nansen-wallet-activity-v1','wallet.activity.analyze','nansen','Nansen wallet transactions','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"creditClass":1,"keyRequired":true}','provider-verified','unknown','direct-http-json','["payment-required","rate-limited"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('nansen-smartmoney-flow-v1','smartmoney.flow.read','nansen','Nansen token flow intelligence','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"creditClass":1,"keyRequired":true}','provider-verified','unknown','direct-http-json','["payment-required","rate-limited"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('agentplace-smartmoney-accumulation-v1','smartmoney.accumulation.detect','agentplace','AgentPlace evidence-derived smart-money accumulation','1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":false,"derived":true}','tested','healthy','derived-intelligence','["insufficient-source-evidence"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('nansen-token-smartmoney-v1','token.smartmoney.read','nansen','Nansen token smart-money intelligence','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"creditClass":1,"keyRequired":true}','provider-verified','unknown','direct-http-json','["payment-required","rate-limited"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('nansen-related-wallets-v1','wallet.cluster.analyze','nansen','Nansen related-wallet relationships','v1','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"creditClass":1,"keyRequired":true}','tested','unknown','direct-http-json','["payment-required","rate-limited"]',10,true,'["development","testnet"]'),
('bubblemaps-token-map-v1','wallet.cluster.analyze','bubblemaps','Bubblemaps holder relationship map','v0','["ethereum","base","arbitrum","bnb","solana"]','{"metered":true,"keyRequired":true}','tested','unknown','direct-http-json','["rate-limited","provider-unavailable"]',20,true,'["development","testnet"]'),
('defillama-protocol-tvl-v1','protocol.tvl.read','defillama','DefiLlama protocol TVL','public-v1','[]','{"metered":false,"keyRequired":false}','provider-verified','healthy','direct-http-json','["rate-limited","protocol-resolution-failed"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('defillama-protocol-yield-v1','protocol.yield.read','defillama','DefiLlama yield pools','public-v1','[]','{"metered":false,"keyRequired":false}','provider-verified','healthy','direct-http-json','["rate-limited"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('defillama-protocol-metrics-v1','protocol.metrics.read','defillama','DefiLlama protocol metadata','public-v1','[]','{"metered":false,"keyRequired":false}','provider-verified','healthy','direct-http-json','["rate-limited","protocol-resolution-failed"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('defillama-stablecoin-supply-v1','stablecoin.supply.read','defillama','DefiLlama stablecoin supply','public-v1','[]','{"metered":false,"keyRequired":false}','provider-verified','healthy','direct-http-json','["rate-limited","asset-resolution-failed"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]'),
('defillama-stablecoin-market-v1','stablecoin.market.read','defillama','DefiLlama stablecoin market context','public-v1','[]','{"metered":false,"keyRequired":false}','provider-verified','healthy','direct-http-json','["rate-limited","asset-resolution-failed"]',10,true,'["development","testnet","staging-mainnet-readonly","production-mainnet"]')
ON CONFLICT (id) DO UPDATE SET version=EXCLUDED.version,supported_networks=EXCLUDED.supported_networks,pricing=EXCLUDED.pricing,trust_status=EXCLUDED.trust_status,health_status=EXCLUDED.health_status,invocation_kind=EXCLUDED.invocation_kind,known_failure_states=EXCLUDED.known_failure_states,priority=EXCLUDED.priority,enabled=EXCLUDED.enabled,environment_eligibility=EXCLUDED.environment_eligibility,updated_at=now();

INSERT INTO worker_capability_route(worker_version_id,canonical_capability_id,suitability) VALUES
('wv-researcher-1','token.market.read','supporting'),('wv-researcher-1','token.liquidity.analyze','supporting'),('wv-researcher-1','token.holders.analyze','supporting'),('wv-researcher-1','token.deployer.analyze','supporting'),('wv-researcher-1','token.security.assess','supporting'),('wv-researcher-1','protocol.tvl.read','primary'),('wv-researcher-1','protocol.yield.read','primary'),('wv-researcher-1','protocol.metrics.read','primary'),('wv-researcher-1','stablecoin.supply.read','primary'),('wv-researcher-1','stablecoin.market.read','primary'),
('wv-memescout-1','token.market.read','primary'),('wv-memescout-1','token.liquidity.analyze','primary'),('wv-memescout-1','token.deployer.analyze','primary'),('wv-memescout-1','token.security.assess','primary'),('wv-memescout-1','smartmoney.flow.read','supporting'),('wv-memescout-1','smartmoney.accumulation.detect','supporting'),('wv-memescout-1','wallet.cluster.analyze','supporting'),('wv-memescout-1','token.smartmoney.read','supporting'),
('wv-smartmoney-1','wallet.profile','primary'),('wv-smartmoney-1','smartmoney.flow.read','primary'),('wv-smartmoney-1','smartmoney.accumulation.detect','primary'),('wv-smartmoney-1','wallet.cluster.analyze','supporting'),('wv-smartmoney-1','token.smartmoney.read','primary')
ON CONFLICT(worker_version_id,canonical_capability_id) DO UPDATE SET suitability=EXCLUDED.suitability,updated_at=now();

UPDATE worker_version SET capability_requirements='["token.market.read","token.liquidity.analyze","token.holders.analyze","token.deployer.analyze","token.security.assess","smartmoney.flow.read","token.smartmoney.read"]'::jsonb WHERE id='wv-memescout-1';
UPDATE job_contract SET default_capability_requirements='["token.market.read","token.liquidity.analyze","token.holders.analyze","token.deployer.analyze","token.security.assess","smartmoney.flow.read","token.smartmoney.read"]'::jsonb WHERE worker_version_id='wv-memescout-1';
UPDATE worker_version SET capability_requirements='["wallet.profile","wallet.performance.analyze","wallet.activity.analyze","smartmoney.flow.read","smartmoney.accumulation.detect","token.smartmoney.read","wallet.cluster.analyze"]'::jsonb WHERE id='wv-smartmoney-1';
UPDATE job_contract SET default_capability_requirements='["wallet.profile","wallet.performance.analyze","wallet.activity.analyze","smartmoney.flow.read","smartmoney.accumulation.detect","token.smartmoney.read","wallet.cluster.analyze"]'::jsonb WHERE worker_version_id='wv-smartmoney-1';
